spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring-jpa-lab}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQL10Dialect}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}